name = "skleinboRegistry"
repo = "https://github.com/skleinbo/JuliaRegistry"
uuid = "b7e9bab0-e757-11e9-222c-cd383ab81b13"

[packages]
aecdbc30-9f0d-11e8-0949-396c5a157264 = { name = "ObservableCollector", path = "O/ObservableCollector" }
