name = "skleinboRegistry"
uuid = "b7e9bab0-e757-11e9-222c-cd383ab81b13"
repo = "https://github.com/skleinbo/JuliaRegistry"

[packages]
2bd58e1e-1b99-47b5-a98e-b1d95625cfec = { name = "VisualGrowthDynamics", path = "V/VisualGrowthDynamics" }
708a6a61-856c-5d7f-acbf-fcf0902d75eb = { name = "GrowthDynamics", path = "G/GrowthDynamics" }
aecdbc30-9f0d-11e8-0949-396c5a157264 = { name = "ObservableCollector", path = "O/ObservableCollector" }
af319372-f9cb-496b-b431-7c8e6f770e40 = { name = "WeightedSampling", path = "W/WeightedSampling" }
b4741b20-32dd-11e9-2e44-23e783dd72cb = { name = "OpenCLPicker", path = "O/OpenCLPicker" }
b5b2f71e-4d2a-452d-9d2b-18613792c179 = { name = "BinaryTrees", path = "B/BinaryTrees" }
fe9c5e76-98a0-40b3-a46c-727041eeba4e = { name = "TreeProcesses", path = "T/TreeProcesses" }
